import{get,setex,del,incr,lpush,ltrim,lrange,hset,hgetall,evalScript,expire}from"./redis";import{decryptJson,encryptJson,randomB64,sha256}from"./crypto";import{assertSafeRemoteUrl,secureEqual,validateProviderInput}from"./security";import{emptyVault,type Vault}from"./types";
const vaultId=process.env.SROUTER_VAULT_ID||"default",instance=process.env.SROUTER_INSTANCE_ID||"primary",ns=`srouter:${vaultId}`,META=`${ns}:meta`,VAULT=`${ns}:vault`,VERSION=`${ns}:version`;type Meta={salt:string;verifier:string};
const SETUP_LUA=`if redis.call('EXISTS',KEYS[1])==1 then return 0 end redis.call('SET',KEYS[1],ARGV[1]) redis.call('SET',KEYS[2],ARGV[2]) redis.call('SET',KEYS[3],'1') return 1`;

export async function isSetup(){return Boolean(await get(META))}
export async function setup(secret:string){if(secret.length<16||secret.length>256)throw new Error("Router Secret harus 16–256 karakter");const salt=randomB64(),v=emptyVault(),meta=JSON.stringify({salt,verifier:await sha256(secret+salt)}),payload=await encryptJson(v,secret,salt);const ok=await evalScript<number>(SETUP_LUA,[META,VAULT,VERSION],[meta,payload]);if(!ok)throw new Error("SRouter sudah disiapkan");await heartbeat();return v}
export async function loadVault(secret:string){if(!secret)throw new Error("UNAUTHORIZED");const raw=await get(META);if(!raw)throw new Error("SETUP_REQUIRED");const m=JSON.parse(raw)as Meta;if(!secureEqual(await sha256(secret+m.salt),m.verifier))throw new Error("UNAUTHORIZED");const p=await get(VAULT);if(!p)throw new Error("Vault tidak ditemukan");const v=await decryptJson<Vault>(p,secret,m.salt);await heartbeat();return{...v,logLimit:v.logLimit||1000,modelFavorites:v.modelFavorites||[],providers:v.providers.map(p=>({...p,models:p.models||[],capabilities:p.capabilities||["chat"],relays:p.relays||[],modelSync:p.modelSync||{status:"idle",modelsCount:p.models?.length||0},pricing:p.pricing||{default:{mode:"unknown"}}})),routes:Object.fromEntries(Object.entries(v.routes||{}).map(([alias,targets])=>[alias,targets.map((target,index)=>({...target,priority:target.priority??index+1,retry:target.retry??0}))]))}}
export async function saveVault(secret:string,v:Vault,expected?:number){for(const p of v.providers){validateProviderInput(p);await assertSafeRemoteUrl(p.baseUrl);for(const relay of p.relays||[])await assertSafeRemoteUrl(relay.url);if(p.oauth){await assertSafeRemoteUrl(p.oauth.authorizeUrl);await assertSafeRemoteUrl(p.oauth.tokenUrl)}}if(Object.keys(v.routes).length>500)throw new Error("Terlalu banyak rute");const current=await loadVault(secret),wanted=expected??current.version;if(current.version!==wanted)throw new Error("VERSION_CONFLICT");const m=JSON.parse((await get(META))!)as Meta,next={...v,version:wanted+1,updatedAt:new Date().toISOString()},payload=await encryptJson(next,secret,m.salt);const script=`local v=tonumber(redis.call('GET',KEYS[1]) or ARGV[1]) if v~=tonumber(ARGV[1]) then return 0 end redis.call('SET',KEYS[2],ARGV[2]) redis.call('SET',KEYS[1],ARGV[3]) return 1`;const ok=await evalScript<number>(script,[VERSION,VAULT],[wanted,payload,next.version]);if(!ok)throw new Error("VERSION_CONFLICT");return next}
export async function nextCounter(id:string){return(await incr(`${ns}:rr:${id}`))||1}export async function setCooldown(id:string,seconds:number){await setex(`${ns}:cool:${id}`,seconds,"1")}export async function isCooling(id:string){return Boolean(await get(`${ns}:cool:${id}`))}
export async function addLog(x:unknown,limit=1000){await lpush(`${ns}:logs`,JSON.stringify(x));await ltrim(`${ns}:logs`,0,Math.max(10,Math.min(limit,5000))-1)}export async function logs(limit=1000){return((await lrange(`${ns}:logs`,0,Math.max(1,Math.min(limit,5000))-1))||[]).map(x=>JSON.parse(x))}export async function clearLogs(){await del(`${ns}:logs`)}
export async function putOAuthState(state:string,value:string){await setex(`${ns}:oauth:${state}`,600,value)}export async function takeOAuthState(state:string){const k=`${ns}:oauth:${state}`,v=await get(k);if(v)await del(k);return v}
export async function heartbeat(){await hset(`${ns}:instances`,instance,JSON.stringify({id:instance,lastSeen:new Date().toISOString()}));await expire(`${ns}:instances`,86400*30)}export async function instances(){const a=(await hgetall(`${ns}:instances`))||[];const out=[];for(let i=1;i<a.length;i+=2)try{out.push(JSON.parse(a[i]))}catch{}return out}
